version: '1.0'
name: test
displayName: test
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
stages:
  - name: stage-e5c34b9d
    displayName: 编译运行
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: 基于镜像的脚本执行
        certificate: ''
        image: ubuntu:22.04
        command:
          - apt update
          - apt install -y build-essential
          - cd test
          - make
          - ./main
        notify: []
        strategy:
          retry: '0'
